title: Michael Ledet
author:
   email: michaelledet@gmail.com
remote_theme: jekyll/minima@1e8a445
minima:   
   skin: dark
   social_links:
      - title: ledemi
        icon: github
        url: "https://github.com/ledemi"
