theme: minima
minima:
   title: Michael Ledet
   author: 
      name: Michael Ledet
      email: michaelledet@gmail.com
   description: personal GitHub Page
      skin: dark
      social_links:
         title: My GitHub
         icon: github
         url: "https://github.com/ledemi"
